apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret-admin
  namespace: kube-system 
type: "kubernetes.io/rbd"
data:
#Please note this value is base64 encoded.
  key: QVFDZUhPMVpJTFBQRFJBQTd6dzNkNzZicGxrdlR3em9vc3lidkE9PQo=
type: kubernetes.io/rbd
---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret-user
type: "kubernetes.io/rbd"  
data:
#Please note this value is base64 encoded.
  key: QVFDZDR1MVoxSDI0QnhBQWFxdmZIRnFuMSs0RFZlK1pRZ0ZmUEE9PQo=
