# need for docker build
sudo: true

language: go
branches:
  only:
    - master
    - csi-v1.0

go: 1.11.x

env:
  global:
    - GO_METALINTER_VERSION="v3.0.0"

install:
  # install gometalinter
  - >
    curl -L
    'https://github.com/alecthomas/gometalinter/blob/v3.0.0/scripts/install.sh'
    | bash -s -- -b $GOPATH/bin "${GO_METALINTER_VERSION}"

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)

script:
  - gometalinter --deadline=10m -j 4 --enable=misspell --enable=staticcheck --vendor ./...
  - test -z $(gofmt -s -l $GO_FILES)
  - make rbdplugin
  - make cephfsplugin

deploy:
  - provider: script
    script:
      - ./deploy.sh
    on:
      all_branches: true
