# need for docker build
sudo: true

language: go
branches:
  only:
    - master
    - csi-v1.0

go: 1.11.x

install:
  - curl -L https://git.io/vp6lP | sh

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - go get -u golang.org/x/lint/golint #go get github.com/golang/lint/golint

script:
  - gometalinter --deadline=10m -j 4 --disable=gocyclo --enable=gosimple --enable=misspell --enable=unused --enable=unparam --enable=staticcheck --vendor ./...
  - test -z $(gofmt -s -l $GO_FILES)
  - make rbdplugin
  - make cephfsplugin

deploy:
  - provider: script
    script:
      - ./deploy.sh
    on:
      all_branches: true
