language: go
branches:
  only:
    - master

go: 1.9.x

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - go get github.com/golang/lint/golint

script:
  - test -z $(gofmt -s -l $GO_FILES)
  - go vet -v $(go list ./... | grep -v /vendor/)

after_success:
  - if [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      sudo bash -c 'docker login -u "${QUAY_IO_USERNAME}" -p "${QUAY_IO_PASSWORD}" quay.io ; make push-container';
    fi
