---
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: default
data:
  # Required for statically provisioned volumes
  userID: BASE64-ENCODED-VALUE
  userKey: BASE64-ENCODED-VALUE

  # Required for dynamically provisioned volumes
  adminID: BASE64-ENCODED-VALUE
  adminKey: BASE64-ENCODED-VALUE
