---
apiVersion: v1
appVersion: "1.0.0"
description: "Container Storage Interface (CSI) driver,
provisioner, and attacher for Ceph cephfs"
name: ceph-csi-cephfs
<<<<<<< HEAD
version: 0.6.0
=======
version: 0.5.3
>>>>>>> 882bebf1d8507d6bcd4b4bfae23a861057353785
keywords:
  - ceph
  - cephfs
  - ceph-csi
home: https://github.com/ceph/ceph-csi
sources:
  - https://github.com/ceph/ceph-csi/tree/csi-v1.0/deploy/cephfs/helm
