apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-cephfs
provisioner: csi-cephfsplugin
parameters:
  # The driver can use either ceph-fuse (fuse) or ceph kernel client (kernel)
  mounter: fuse

  monitors: mon1:port,mon2:port
  rootPath: /
  user: admin

  csiProvisionerSecretName: csi-cephfs-secret
  csiProvisionerSecretNameSpace: default
reclaimPolicy: Delete
