apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-cephfs
provisioner: csi-cephfsplugin
parameters:
  monitors: mon1:port,mon2:port

  # If set to true, a new volume will be created along with a RADOS user - this requires admin access.
  # If set to false, it is assumed the volume already exists and the user is expected to provide
  # a rootPath to a cephfs volume and user credentials.
  provisionVolume: "true"

  # Required if provisionVolume is set to false
  # rootPath: /path-in-cephfs

  # Required if provisionVolume is set to true
  # pool: cephfs_data

  # The secret has to contain user and/or admin credentials.
  csiProvisionerSecretName: csi-cephfs-secret
  csiProvisionerSecretNameSpace: default

  # (optional) The driver can use either ceph-fuse (fuse) or ceph kernel client (kernel)
  # If left out, default volume mounter will be used - this is determined by probing for ceph-fuse
  # or by setting the default mounter explicitly via --volumemounter command-line argument.
  # mounter: kernel
reclaimPolicy: Delete
