apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: default
data:
  # Required if provisionVolume is set to false
  userID: userID-encoded-by-base64
  userKey: userKey-encoded-by-base64

  # Required if provisionVolume is set to true
  adminID: adminID-encoded-by-base64
  adminKey: adminKey-encoded-by-base64
