apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: csi-rbd
provisioner: csi-rbdplugin 
parameters:
    monitors: 192.168.80.233:6789
    pool: kubernetes
    csiProvisionerSecretName: csi-ceph-secret 
    csiProvisionerSecretNamespace: default 
reclaimPolicy: Delete 
